/*
 * Copyright (c) 2026 Enaium
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package cn.enaium.allinstats.db

import org.babyfish.jimmer.kt.new
import org.babyfish.jimmer.sql.dialect.H2Dialect
import org.babyfish.jimmer.sql.kt.KSqlClient
import org.babyfish.jimmer.sql.kt.ast.expression.*
import org.babyfish.jimmer.sql.kt.newKSqlClient
import org.babyfish.jimmer.sql.runtime.ConnectionManager
import org.babyfish.jimmer.sql.runtime.DefaultDatabaseNamingStrategy
import java.time.LocalDateTime
import java.time.ZoneId

object StatsSchema {
    private val statements = listOf(
        """
        CREATE TABLE IF NOT EXISTS stat_world (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            world_id VARCHAR(255) NOT NULL,
            name VARCHAR(255) NOT NULL,
            created_time TIMESTAMP NOT NULL,
            modified_time TIMESTAMP NOT NULL
        )
        """.trimIndent(),
        "CREATE UNIQUE INDEX IF NOT EXISTS stat_world_world_id_uq ON stat_world (world_id)",
        """
        CREATE TABLE IF NOT EXISTS stat_player (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            world_id VARCHAR(255) NOT NULL,
            uuid VARCHAR(64) NOT NULL,
            name VARCHAR(255) NOT NULL,
            created_time TIMESTAMP NOT NULL,
            modified_time TIMESTAMP NOT NULL
        )
        """.trimIndent(),
        "CREATE UNIQUE INDEX IF NOT EXISTS stat_player_uq ON stat_player (world_id, uuid)",
        """
        CREATE TABLE IF NOT EXISTS stat_counter (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            world_id VARCHAR(255) NOT NULL,
            player_uuid VARCHAR(64) NOT NULL,
            type VARCHAR(64) NOT NULL,
            stat_key VARCHAR(255) NOT NULL,
            source VARCHAR(32) NOT NULL,
            bucket BIGINT NOT NULL,
            amount BIGINT NOT NULL
        )
        """.trimIndent(),
        "CREATE UNIQUE INDEX IF NOT EXISTS stat_counter_uq ON stat_counter (world_id, player_uuid, type, stat_key, source, bucket)",
        "CREATE INDEX IF NOT EXISTS stat_counter_query_idx ON stat_counter (world_id, player_uuid, type, stat_key, bucket)",
    )

    fun create(dataSource: SimpleDataSource) {
        dataSource.connection.use { connection ->
            connection.createStatement().use { statement ->
                statements.forEach(statement::execute)
            }
        }
    }
}

/**
 * Everything that touches the statistics database goes through this class. Reads are plain queries,
 * writes are merged into the unique counter key (world, player, type, key, source, minute).
 */
class StatsDatabase(url: String) {
    private val dataSource = SimpleDataSource(url)

    private companion object {
        const val UPDATE_COUNTER =
            "UPDATE stat_counter SET amount = amount + ? WHERE world_id = ? AND player_uuid = ? " +
                "AND type = ? AND stat_key = ? AND source = ? AND bucket = ?"

        const val INSERT_COUNTER =
            "INSERT INTO stat_counter (world_id, player_uuid, type, stat_key, source, bucket, amount) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?)"
    }

    val sql: KSqlClient = newKSqlClient {
        setConnectionManager(ConnectionManager.simpleConnectionManager(dataSource))
        setDatabaseNamingStrategy(DefaultDatabaseNamingStrategy.LOWER_CASE)
        setDialect(H2Dialect())
    }

    init {
        StatsSchema.create(dataSource)
    }

    /**
     * The worlds of the database, the one that was played last comes first.
     */
    fun worldIds(): List<WorldRow> {
        val activity = worldActivity()
        return sql.createQuery(StatWorld::class) {
            select(table)
        }.execute()
            .map { WorldRow(it.worldId, it.name, it.modifiedTime.toEpochMilli(), activity[it.worldId] ?: 0L) }
            .sortedWith(compareByDescending<WorldRow> { it.lastBucket }.thenByDescending { it.modifiedTime })
    }

    /**
     * The newest minute of every world, used to know which world was played last.
     */
    private fun worldActivity(): Map<String, Long> =
        sql.createQuery(StatCounter::class) {
            groupBy(table.worldId)
            select(table.worldId, max(table.bucket))
        }.execute().associate { (world, bucket) -> world to (bucket ?: 0L) }

    fun ensureWorld(worldId: String, name: String) {
        val now = LocalDateTime.now()
        val existing = sql.createQuery(StatWorld::class) {
            where(table.worldId eq worldId)
            select(table)
        }.fetchOneOrNull()
        if (existing == null) {
            sql.save(
                new(StatWorld::class).by {
                    this.worldId = worldId
                    this.name = name
                    this.createdTime = now
                    this.modifiedTime = now
                }
            )
        } else if (existing.name != name) {
            sql.save(
                new(StatWorld::class).by {
                    this.id = existing.id
                    this.worldId = worldId
                    this.name = name
                    this.createdTime = existing.createdTime
                    this.modifiedTime = now
                }
            )
        }
    }

    fun players(worldId: String): List<PlayerRow> =
        sql.createQuery(StatPlayer::class) {
            where(table.worldId eq worldId)
            orderBy(table.modifiedTime.desc())
            select(table)
        }.execute().map { PlayerRow(it.worldId, it.uuid, it.name) }

    fun ensurePlayer(worldId: String, uuid: String, name: String) {
        val now = LocalDateTime.now()
        val existing = sql.createQuery(StatPlayer::class) {
            where(table.worldId eq worldId, table.uuid eq uuid)
            select(table)
        }.fetchOneOrNull()
        if (existing == null) {
            sql.save(
                new(StatPlayer::class).by {
                    this.worldId = worldId
                    this.uuid = uuid
                    this.name = name
                    this.createdTime = now
                    this.modifiedTime = now
                }
            )
        } else if (existing.name != name) {
            sql.save(
                new(StatPlayer::class).by {
                    this.id = existing.id
                    this.worldId = worldId
                    this.uuid = uuid
                    this.name = name
                    this.createdTime = existing.createdTime
                    this.modifiedTime = now
                }
            )
        }
    }

    /**
     * Adds the counters to their bucket. The amount of a bucket is incremented instead of replaced,
     * so a bucket can be written while its minute is still running and what was just recorded shows
     * up in the interface right away.
     *
     * The two statements are written here instead of using the save command of the ORM: saving an
     * entity writes the amount it carries (it would replace the value of a bucket that was written
     * before) and an atomic increment is not part of its API. Everything else goes through the ORM.
     */
    fun addCounters(rows: List<CounterRow>) {
        if (rows.isEmpty()) {
            return
        }
        dataSource.connection.use { connection ->
            connection.autoCommit = false
            connection.prepareStatement(UPDATE_COUNTER).use { update ->
                connection.prepareStatement(INSERT_COUNTER).use { insert ->
                    rows.forEach { row ->
                        update.setLong(1, row.amount)
                        update.setString(2, row.worldId)
                        update.setString(3, row.playerUuid)
                        update.setString(4, row.type)
                        update.setString(5, row.statKey)
                        update.setString(6, row.source)
                        update.setLong(7, row.bucket)
                        if (update.executeUpdate() == 0) {
                            insert.setString(1, row.worldId)
                            insert.setString(2, row.playerUuid)
                            insert.setString(3, row.type)
                            insert.setString(4, row.statKey)
                            insert.setString(5, row.source)
                            insert.setLong(6, row.bucket)
                            insert.setLong(7, row.amount)
                            insert.executeUpdate()
                        }
                    }
                }
            }
            connection.commit()
        }
    }

    fun keyTotals(
        worldId: String,
        playerUuid: String?,
        types: List<String>,
        sources: List<String>?,
        search: String,
        from: Long,
        to: Long,
        limit: Int,
    ): List<KeyTotal> {
        if (types.isEmpty()) {
            return emptyList()
        }
        return sql.createQuery(StatCounter::class) {
            where(table.worldId eq worldId)
            if (playerUuid != null) {
                where(table.playerUuid eq playerUuid)
            }
            where(table.type valueIn types)
            if (sources != null) {
                where(table.source valueIn sources)
            }
            if (search.isNotEmpty()) {
                where(table.statKey like search)
            }
            where(table.bucket ge from)
            where(table.bucket lt to)
            groupBy(table.statKey)
            orderBy(sum(table.amount).desc())
            select(table.statKey, sum(table.amount))
        }.limit(limit).execute().map { (key, total) -> KeyTotal(key, total ?: 0L) }
    }

    /**
     * Totals of every (type, source) pair of a single key, used by the summary panel.
     */
    fun totals(
        worldId: String,
        playerUuid: String?,
        types: List<String>,
        sources: List<String>?,
        statKey: String,
        from: Long,
        to: Long,
    ): List<TypeTotal> {
        if (types.isEmpty()) {
            return emptyList()
        }
        return sql.createQuery(StatCounter::class) {
            where(table.worldId eq worldId)
            if (playerUuid != null) {
                where(table.playerUuid eq playerUuid)
            }
            where(table.type valueIn types)
            if (sources != null) {
                where(table.source valueIn sources)
            }
            where(table.statKey eq statKey)
            where(table.bucket ge from)
            where(table.bucket lt to)
            groupBy(table.type, table.source)
            select(table.type, table.source, sum(table.amount))
        }.execute().map { (type, source, total) -> TypeTotal(type, source, total ?: 0L) }
    }

    fun minutes(
        worldId: String,
        playerUuid: String?,
        types: List<String>,
        sources: List<String>?,
        statKey: String,
        from: Long,
        to: Long,
    ): List<MinutePoint> {
        if (types.isEmpty()) {
            return emptyList()
        }
        return sql.createQuery(StatCounter::class) {
            where(table.worldId eq worldId)
            if (playerUuid != null) {
                where(table.playerUuid eq playerUuid)
            }
            where(table.type valueIn types)
            if (sources != null) {
                where(table.source valueIn sources)
            }
            where(table.statKey eq statKey)
            where(table.bucket ge from)
            where(table.bucket lt to)
            groupBy(table.type, table.source, table.bucket)
            orderBy(table.bucket.asc())
            select(table.type, table.source, table.bucket, sum(table.amount))
        }.execute().map { (type, source, bucket, total) -> MinutePoint(type, source, bucket, total ?: 0L) }
    }

    /**
     * The minutes of several counters at once, grouped by the counter and the minute. Used to draw
     * more than one counter in the same chart.
     */
    fun minutesOfKeys(
        worldId: String,
        playerUuid: String?,
        types: List<String>,
        sources: List<String>?,
        keys: List<String>,
        from: Long,
        to: Long,
    ): List<KeyMinutePoint> {
        if (types.isEmpty() || keys.isEmpty()) {
            return emptyList()
        }
        return sql.createQuery(StatCounter::class) {
            where(table.worldId eq worldId)
            if (playerUuid != null) {
                where(table.playerUuid eq playerUuid)
            }
            where(table.type valueIn types)
            if (sources != null) {
                where(table.source valueIn sources)
            }
            where(table.statKey valueIn keys)
            where(table.bucket ge from)
            where(table.bucket lt to)
            groupBy(table.statKey, table.type, table.source, table.bucket)
            orderBy(table.bucket.asc())
            select(table.statKey, table.type, table.source, table.bucket, sum(table.amount))
        }.execute().map { (key, type, source, bucket, total) ->
            KeyMinutePoint(key, type, source, bucket, total ?: 0L)
        }
    }

    /**
     * The newest minute that holds data of a world, used to pick a default time range.
     */
    fun lastBucket(worldId: String, playerUuid: String? = null): Long? =
        sql.createQuery(StatCounter::class) {
            where(table.worldId eq worldId)
            if (playerUuid != null) {
                where(table.playerUuid eq playerUuid)
            }
            select(max(table.bucket))
        }.fetchOneOrNull()
}

private fun LocalDateTime.toEpochMilli(): Long =
    atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()

data class WorldRow(
    val worldId: String,
    val name: String,
    val modifiedTime: Long,
    val lastBucket: Long = 0L,
)

data class PlayerRow(val worldId: String, val uuid: String, val name: String)

data class CounterRow(
    val worldId: String,
    val playerUuid: String,
    val type: String,
    val statKey: String,
    val source: String,
    val bucket: Long,
    val amount: Long,
)

data class KeyTotal(val key: String, val total: Long)

data class TypeTotal(val type: String, val source: String, val total: Long)

data class MinutePoint(val type: String, val source: String, val bucket: Long, val amount: Long)

data class KeyMinutePoint(
    val key: String,
    val type: String,
    val source: String,
    val bucket: Long,
    val amount: Long,
)
